export const Languages = [
    {code: 'en', name: "English"},
    {code: 'fr', name: "French"},
    {code: 'es', name: "Spanish"},
    {code: 'ar', name: "Arabic"},
    {code: 'bg', name: "Bulgarian"},
    {code: 'ca', name: "Catalan"},
    {code: 'cz', name: "Czech"},
    {code: 'de', name: "German"},
    {code: 'el', name: "Greek"},
    {code: 'fa', name: "Persian"},
    {code: 'fi', name: "Finish"},
    {code: 'gl', name: "Galician"},
    {code: 'hr', name: "Croatian"},
    {code: 'hu', name: "Hungarian"},
    {code: 'it', name: "Italian"},
    {code: 'ja', name: "Japanese"},
    {code: 'kr', name: "Korean"},
    {code: 'la', name: "Latvian"},
    {code: 'lt', name: "Lithuanian"},
    {code: 'mk', name: "Macedonian"},
    {code: 'nl', name: "Dutch"},
    {code: 'pl', name: "Polish"},
    {code: 'pt', name: "Portuguese"},
    {code: 'ro', name: "Romanian"},
    {code: 'ru', name: "Russian"},
    {code: 'se', name: "Swedish"},
    {code: 'sk', name: "Slovak"},
    {code: 'sl', name: "Slovenian"},
    {code: 'tr', name: "Turkish"},
    {code: 'ua', name: "Ukrainian"},
    {code: 'vi', name: "Vietnamese"},
    {code: 'zh_cn', name: "Chinese Simplified"},
    {code: 'zh_tw', name: "Chinese Traditional"}
  ]
